import type { PromptIntent } from '../agent/generate';

export type AlertArtifact = {
  alertSearch: string;
  condition: string;
  cronSchedule: string;
  description: string;
  savedSearchConf: string;
  title: string;
};

export function generateAlertArtifact(prompt: string, intent: PromptIntent, spl: string): AlertArtifact | undefined {
  if (intent.artifact !== 'alert' && intent.artifact !== 'dashboard+alert') {
    return undefined;
  }

  if (intent.threshold === undefined) {
    return undefined;
  }

  const span = toSplunkSpan(intent.thresholdWindow ?? '5 minutes');
  const metric = metricName(intent);
  const baseSearch = extractBaseSearch(spl, intent);
  const title = buildTitle(prompt, intent);
  const cronSchedule = spanToCron(span);
  const alertSearch = [
    baseSearch,
    `| bin _time span=${span}`,
    `| stats count as ${metric} by _time`,
    `| where ${metric} > ${intent.threshold}`,
    '| sort _time',
  ].join(' ');
  const condition = `${metric} > ${intent.threshold} in ${intent.thresholdWindow ?? span}`;
  const description = `Generated by SPL Forge from prompt: ${prompt}`;

  return {
    alertSearch,
    condition,
    cronSchedule,
    description,
    savedSearchConf: buildSavedSearchConf(title, description, alertSearch, cronSchedule),
    title,
  };
}

function buildSavedSearchConf(title: string, description: string, alertSearch: string, cronSchedule: string) {
  return [
    `[${title}]`,
    `description = ${description}`,
    `search = ${alertSearch}`,
    'disabled = 1',
    'is_scheduled = 1',
    `cron_schedule = ${cronSchedule}`,
    'alert_type = number of events',
    'alert_comparator = greater than',
    'alert_threshold = 0',
    'alert.suppress = 0',
  ].join('\n');
}

function extractBaseSearch(spl: string, intent: PromptIntent) {
  const head = spl.split('|')[0]?.trim();

  if (head) {
    return head;
  }

  const parts = ['index=main', 'sourcetype=auth'];

  if (intent.wantsFailedLogins) {
    parts.push('action=failure');
  }

  if (intent.wantsSuccessLogins) {
    parts.push('action=success');
  }

  parts.push('latest=now');
  return parts.join(' ');
}

function buildTitle(prompt: string, intent: PromptIntent) {
  if (intent.wantsFailedLogins) {
    return 'Failed Login Threshold Alert';
  }

  if (intent.wantsSuccessLogins) {
    return 'Successful Login Threshold Alert';
  }

  return titleCase(prompt.replace(/[^\w\s-]/g, '').trim().slice(0, 64) || 'SPL Forge Alert');
}

function titleCase(value: string) {
  return value
    .split(/\s+/)
    .filter(Boolean)
    .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1).toLowerCase()}`)
    .join(' ');
}

function metricName(intent: PromptIntent) {
  if (intent.wantsSuccessLogins) {
    return 'successful_logins';
  }

  if (intent.wantsFailedLogins) {
    return 'failed_logins';
  }

  return 'event_count';
}

function toSplunkSpan(window: string) {
  const match = window.match(/(\d+)\s*(minute|minutes|min|m|hour|hours|h|day|days|d)/i);

  if (!match) {
    return '5m';
  }

  const [, amount, unit] = match;
  const lowerUnit = unit.toLowerCase();

  if (lowerUnit === 'm' || lowerUnit.startsWith('min')) {
    return `${amount}m`;
  }

  if (lowerUnit === 'h' || lowerUnit.startsWith('hour')) {
    return `${amount}h`;
  }

  if (lowerUnit === 'd' || lowerUnit.startsWith('day')) {
    return `${amount}d`;
  }

  return '5m';
}

function spanToCron(span: string) {
  const minutes = span.match(/^(\d+)m$/);

  if (minutes) {
    return `*/${minutes[1]} * * * *`;
  }

  const hours = span.match(/^(\d+)h$/);

  if (hours) {
    return `0 */${hours[1]} * * *`;
  }

  return '*/5 * * * *';
}
