import type { PromptIntent } from '../agent/generate';
import type { SplunkSearchResult } from '../splunk/execute';

export type DashboardArtifact = {
  dashboardJson: string;
  description: string;
  fields: string[];
  sourceSearch: string;
  title: string;
  visualizationType: 'bar' | 'line' | 'singlevalue' | 'table';
};

type DashboardDefinition = {
  dataSources: Record<string, unknown>;
  description: string;
  layout: Record<string, unknown>;
  title: string;
  visualizations: Record<string, unknown>;
};

export function generateDashboardArtifact(
  prompt: string,
  intent: PromptIntent,
  spl: string,
  execution: SplunkSearchResult,
): DashboardArtifact | undefined {
  if (intent.artifact !== 'dashboard' && intent.artifact !== 'dashboard+alert') {
    return undefined;
  }

  const fields = execution.fields.length > 0 ? execution.fields : inferFieldsFromSearch(spl);
  const visualizationType = chooseVisualization(intent, fields);
  const title = buildTitle(prompt, intent);
  const description = `Generated by SPL Forge from prompt: ${prompt}`;
  const definition = buildDashboardDefinition(title, description, spl, visualizationType);

  return {
    dashboardJson: JSON.stringify(definition, null, 2),
    description,
    fields,
    sourceSearch: spl,
    title,
    visualizationType,
  };
}

function buildDashboardDefinition(
  title: string,
  description: string,
  spl: string,
  visualizationType: DashboardArtifact['visualizationType'],
): DashboardDefinition {
  const chartType = visualizationType === 'line'
    ? 'splunk.line'
    : visualizationType === 'singlevalue'
      ? 'splunk.singlevalue'
      : visualizationType === 'bar'
        ? 'splunk.bar'
        : 'splunk.table';

  return {
    dataSources: {
      ds_primary: {
        options: {
          query: spl,
        },
        type: 'ds.search',
      },
    },
    description,
    layout: {
      options: {
        height: 960,
        width: 1440,
      },
      structure: [
        {
          item: 'viz_primary',
          position: {
            h: 420,
            w: 1440,
            x: 0,
            y: 0,
          },
          type: 'block',
        },
        {
          item: 'viz_table',
          position: {
            h: 420,
            w: 1440,
            x: 0,
            y: 430,
          },
          type: 'block',
        },
      ],
      type: 'grid',
    },
    title,
    visualizations: {
      viz_primary: {
        dataSources: {
          primary: 'ds_primary',
        },
        options: {},
        title: primaryVisualizationTitle(visualizationType),
        type: chartType,
      },
      viz_table: {
        dataSources: {
          primary: 'ds_primary',
        },
        options: {},
        title: 'Result rows',
        type: 'splunk.table',
      },
    },
  };
}

function chooseVisualization(intent: PromptIntent, fields: string[]): DashboardArtifact['visualizationType'] {
  if (intent.wantsTrend || fields.includes('_time')) {
    return 'line';
  }

  const metricField = fields.find((field) => /count|logins|events|total/.test(field));
  const dimensionFields = fields.filter((field) => field !== metricField && !field.startsWith('_'));

  if (metricField && dimensionFields.length > 0) {
    return 'bar';
  }

  if (metricField) {
    return 'singlevalue';
  }

  return 'table';
}

function primaryVisualizationTitle(type: DashboardArtifact['visualizationType']) {
  if (type === 'line') {
    return 'Trend';
  }

  if (type === 'singlevalue') {
    return 'Metric';
  }

  if (type === 'bar') {
    return 'Breakdown';
  }

  return 'Rows';
}

function buildTitle(prompt: string, intent: PromptIntent) {
  if (intent.wantsFailedLogins) {
    return 'Failed Login Dashboard';
  }

  if (intent.wantsSuccessLogins) {
    return 'Successful Login Dashboard';
  }

  const compact = prompt
    .replace(/[^\w\s-]/g, '')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, 64);

  return compact ? titleCase(compact) : 'SPL Forge Dashboard';
}

function titleCase(value: string) {
  return value
    .split(' ')
    .filter(Boolean)
    .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1).toLowerCase()}`)
    .join(' ');
}

function inferFieldsFromSearch(spl: string) {
  const statsMatch = spl.match(/\|\s*stats\s+count\s+as\s+(\w+)(?:\s+by\s+([^|]+))?/i);

  if (!statsMatch) {
    return [];
  }

  const metric = statsMatch[1];
  const dimensions = statsMatch[2]?.trim().split(/\s+/).filter(Boolean) ?? [];
  return [...dimensions, metric];
}
