import type { ForgeRunResult } from '../agent/workflow';
import { buildClassicDashboardXml } from './dashboard';

export type SplunkAppPackage = {
  appId: string;
  files: Record<string, string>;
  manifest: {
    alert?: string;
    dashboard?: string;
    finalSpl: string;
    prompt: string;
    rowCount: number;
  };
  rootDir: string;
};

export function buildSplunkAppPackage(options: { appId?: string; result: ForgeRunResult }): SplunkAppPackage {
  const appId = normalizeAppId(options.appId ?? 'spl_forge_generated_app');
  const { result } = options;
  const files: Record<string, string> = {
    'README.md': buildReadme(result),
    'default/app.conf': buildAppConf(),
    'default/props.conf': buildPropsConf(),
    'default/transforms.conf': buildTransformsConf(),
    'metadata/default.meta': buildDefaultMeta(),
  };

  if (result.dashboard) {
    files[`default/data/ui/views/${result.dashboard.viewName}.xml`] = buildClassicDashboardXml(
      result.dashboard.title,
      result.execution.search,
      result.dashboard.visualizationType,
    );
  }

  files['default/savedsearches.conf'] = result.alert ? buildAlertSavedSearch(result) : buildSavedSearchOnly(result);

  const manifest = {
    alert: result.alert?.title,
    dashboard: result.dashboard?.viewName,
    finalSpl: result.spl,
    prompt: result.prompt,
    rowCount: result.execution.rowCount,
  };

  files['spl-forge-manifest.json'] = JSON.stringify(manifest, null, 2);

  return {
    appId,
    files,
    manifest,
    rootDir: appId,
  };
}

function buildAppConf() {
  return [
    '[install]',
    'is_configured = 1',
    '',
    '[launcher]',
    'author = SPL Forge',
    'description = Generated Splunk app artifacts from SPL Forge.',
    'version = 0.1.0',
    '',
    '[ui]',
    'is_visible = 1',
    'label = SPL Forge Generated App',
  ].join('\n');
}

function buildDefaultMeta() {
  return [
    '[]',
    'access = read : [ * ], write : [ admin ]',
    'export = system',
  ].join('\n');
}

function buildPropsConf() {
  return [
    '[auth]',
    'SHOULD_LINEMERGE = false',
    'INDEXED_EXTRACTIONS = csv',
    'FIELD_NAMES = timestamp,user,src,country,user_agent,action,sourcetype,index',
    'KV_MODE = none',
    '',
    '[auth_complex]',
    'SHOULD_LINEMERGE = false',
    'INDEXED_EXTRACTIONS = csv',
    'FIELD_NAMES = timestamp,user,src,dest,app,country,user_agent,action,outcome,risk_score,mfa_result,role,device,session_id,sourcetype,index',
    'KV_MODE = none',
  ].join('\n');
}

function buildTransformsConf() {
  return [
    '# Reserved for future generated lookup and field-transform stanzas.',
    '# props.conf carries CSV field extraction for validation sourcetypes today.',
  ].join('\n');
}

function buildSavedSearchOnly(result: ForgeRunResult) {
  return [
    '[SPL Forge Generated Search]',
    `description = Generated by SPL Forge from prompt: ${result.prompt}`,
    `search = ${result.execution.search}`,
    'disabled = 1',
    'is_scheduled = 0',
  ].join('\n');
}

function buildAlertSavedSearch(result: ForgeRunResult) {
  const alert = result.alert;

  if (!alert) {
    return buildSavedSearchOnly(result);
  }

  const metric = alert.alertSearch.match(/\|\s*stats\s+count\s+as\s+([A-Za-z_][\w]*)\s+by\s+_time/i)?.[1] ?? 'event_count';
  const threshold = alert.alertSearch.match(/\|\s*where\s+[A-Za-z_][\w]*\s*>\s*(\d+)/i)?.[1] ?? '0';
  const span = alert.alertSearch.match(/\|\s*bin\s+_time\s+span=([^\s|]+)/i)?.[1] ?? '5m';
  const alertSearch = [
    extractExecutableBase(result.execution.search),
    `| bin _time span=${span}`,
    `| stats count as ${metric} by _time`,
    `| where ${metric} > ${threshold}`,
    '| sort _time',
  ].join(' ');

  return [
    `[${alert.title}]`,
    `description = ${alert.description}`,
    `search = ${alertSearch}`,
    'disabled = 1',
    'is_scheduled = 1',
    `cron_schedule = ${alert.cronSchedule}`,
    'alert_type = number of events',
    'alert_comparator = greater than',
    'alert_threshold = 0',
    'alert.suppress = 0',
  ].join('\n');
}

function extractExecutableBase(search: string) {
  const parts = search
    .split('|')
    .map((part) => part.trim())
    .filter(Boolean);
  const baseParts: string[] = [];

  for (const part of parts) {
    if (/^(stats|timechart|chart|table|sort|fields)\b/i.test(part)) {
      break;
    }

    baseParts.push(part);
  }

  return baseParts.join(' | ') || search;
}

function buildReadme(result: ForgeRunResult) {
  return [
    '# SPL Forge Generated App',
    '',
    'Generated by SPL Forge from validated Splunk execution.',
    '',
    '## Prompt',
    '',
    result.prompt,
    '',
    '## Final SPL',
    '',
    '```spl',
    result.spl,
    '```',
    '',
    '## Executable Search Used For Packaged Dashboard',
    '',
    '```spl',
    result.execution.search,
    '```',
    '',
    '## Verification',
    '',
    `- Execution mode: ${result.execution.mode}`,
    `- Execution status: ${result.execution.status}`,
    `- Rows verified before export: ${result.execution.rowCount}`,
    `- Fields: ${result.execution.fields.join(', ') || 'none'}`,
    `- Dashboard generated: ${result.dashboard ? 'yes' : 'no'}`,
    `- Disabled alert generated: ${result.alert ? 'yes' : 'no'}`,
    '',
    '## Readiness Notes',
    '',
    '- Generated app includes `props.conf` CSV extraction stanzas for `auth` and `auth_complex` validation sourcetypes.',
    '- REST publish path creates or updates dashboard XML and disabled saved-search alert, then reloads those knowledge-object endpoints.',
    '- Full Splunk app install automation is not claimed here; manual app-folder import remains supported.',
    '- Splunk model generation is configured outside the exported app through MCP AI Assistant tool or Splunk-hosted model endpoint.',
    '',
    '## Manual Import',
    '',
    '1. Review all generated files.',
    '2. Copy this app folder into `$SPLUNK_HOME/etc/apps/`.',
    '3. Restart Splunk or reload apps.',
    '4. Keep alerts disabled until reviewed.',
  ].join('\n');
}

function normalizeAppId(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9_]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .slice(0, 80) || 'spl_forge_generated_app';
}
